title: CATS!
hero_image: images/banner.png
description: Create a simple line-following game in Scratch. Guide the cats to safety, and don't let any fall through the gaps!
listed: true
copyedit: true
version: 4.0.0
last_tested: 2018-10-18
steps:
- title: Introduction
- title: What you will need
- title: Drawing lines
- title: Cloning cats
- title: Moving cats
- title: Sticking to the lines
- title: Getting to safety
- title: "Challenge: More obstacles"
