title: CATS!
hero_image: images/banner.png
description: Create a simple line-following game in Scratch. Guide the cats to safety, and don't let any fall through the gaps!
theme: orange # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
hardware: ''
software: scratch
site_areas: projects
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Drawing lines
- title: Cloning cats
- title: Moving cats
- title: Sticking to the lines
- title: Getting to safety
- title: "Challenge: More obstacles"