---
title: 猫！
hero_image: images/banner.png
description: 创建一个游戏，在游戏中引导猫咪别让它们掉到洞里
listed: true
copyedit: true
version: 4.0.2
last_tested: 2018-10-18
steps:
  - 
    title: 介绍
  - 
    title: 画线
  - 
    title: Clone cats
  - 
    title: Make the cats move
  - 
    title: Stick to the lines
  - 
    title: Get to safety
  - 
    title: "Challenge: more obstacles"
    challenge: true
  - 
    title: What next?
