---
title: GATS!
hero_image: images/banner.png
description: Create a game in which you guide cats to safety and stop them from falling into holes
listed: true
copyedit: true
version: 4.0.2
last_tested: 2018-10-18
steps:
  - 
    title: Introducció
  - 
    title: Dibuixa línies
  - 
    title: Clona gats
  - 
    title: Fes moure els gats
  - 
    title: Adhereix-los a les línies
  - 
    title: Fes que vagin segurs
  - 
    title: "Repte: més obstacles"
    challenge: true
  - 
    title: What next?
