---
title: '¡GATOS!'
hero_image: images/banner.png
description: Crea un juego en el que guíes a los gatos a un lugar seguro y evites que caigan en los agujeros
listed: true
copyedit: true
version: 4.0.2
last_tested: 2018-10-18
steps:
  - 
    title: Introducción
  - 
    title: Dibuja líneas
  - 
    title: Clona gatos
  - 
    title: Haz que los gatos se muevan
  - 
    title: Pegarse a las líneas
  - 
    title: Llegar a un lugar seguro
  - 
    title: "Desafío: Más obstáculos"
    challenge: true
  - 
    title: '¿Qué sigue?'
