---
title: GATTI!
hero_image: images/banner.png
description: Crea un gioco in cui porti i gatti in salvo e impedisci loro di cadere
  nelle buche
listed: true
copyedit: true
version: 4.0.2
last_tested: 2018-10-18
steps:
- title: Introduzione
- title: Traccia delle linee
- title: Clona i gatti
  completion:
  - engaged
- title: Fai muovere i gatti
- title: Aderisci alle linee
- title: Mettiti in salvo
  completion:
  - internal
- title: 'Sfida: Ancora più ostacoli'
  challenge: true